### ISSUE TITLE
`raw_input()` in Python3 file in omnetpp-5.7.1

### ISSUE THREAD

**Issue by Enough7** [omnetpp/omnetpp#1077]
Hi,
the [opp_featuretool](https://github.com/omnetpp/omnetpp/blob/omnetpp-5.7.1/src/utils/opp_featuretool#L1) declares Python3 but afaik uses Python2 in [Line 53](https://github.com/omnetpp/omnetpp/blob/ec6b02909736791b46899eab01fac2a43ccb99d7/src/utils/opp_featuretool#L53)

## Describe the bug
```
$ opp_featuretool disable visualization
Disabling feature(s):  visualization
Dependent features:  configuratortutorial, visualization_examples, visualizationtutorial, visualizershowcases, wirelessshowcases
Disable these features, too? [Y/n] Traceback (most recent call last):
  File "/home/userp/Applications/omnetpp-5.7.1/bin/opp_featuretool", line 864, in <module>
    tool.run()
  File "/home/userp/Applications/omnetpp-5.7.1/bin/opp_featuretool", line 833, in run
    self.doDisableCommand()
  File "/home/userp/Applications/omnetpp-5.7.1/bin/opp_featuretool", line 617, in doDisableCommand
    update = queryYesNo("Disable these features, too?", default="yes")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userp/Applications/omnetpp-5.7.1/bin/opp_featuretool", line 53, in queryYesNo
    choice = raw_input().lower()
             ^^^^^^^^^
NameError: name 'raw_input' is not defined
```

**Comment by rhornig** [comment]
Hmm, indeed. This is a bug. For a quick fix use `input()` instead of `raw_input()`. Sadly this is a bug going back to at least 5.0 version. We can add this fix but whether those will have a release anytime soon is a question. I will also add a hot patch for this in `opp_env`
