### ISSUE TITLE
Unable to install OMNet++6.0.3 with Python 3.12 on Windows 10

### ISSUE THREAD

**Issue by UbomManny** [omnetpp/omnetpp#1257]
Please when I run ./configure OMNet report an error message shown below:

checking for python3... python3
checking if all necessary Python modules are available... Traceback (most recent call last):
  File "<string>", line 34, in <module>
  File "C:/omnetpp-6.0.3-windows-x86_64/omnetpp-6.0.3/python/omnetpp/scave/utils.py", line 21, in <module>
    import scipy.stats as st
  File "C:/omnetpp-6.0.3-windows-x86_64/omnetpp-6.0.3/tools/win32.x86_64/mingw64/lib/python3.10/site-packages/scipy/stats/__init__.py", line 467, in <module>
    from ._stats_py import *
  File "C:/omnetpp-6.0.3-windows-x86_64/omnetpp-6.0.3/tools/win32.x86_64/mingw64/lib/python3.10/site-packages/scipy/stats/_stats_py.py", line 40, in <module>
    from scipy.ndimage import _measurements
  File "C:/omnetpp-6.0.3-windows-x86_64/omnetpp-6.0.3/tools/win32.x86_64/mingw64/lib/python3.10/site-packages/scipy/ndimage/__init__.py", line 151, in <module>
    from ._filters import *  # noqa: F401 F403
  File "C:/omnetpp-6.0.3-windows-x86_64/omnetpp-6.0.3/tools/win32.x86_64/mingw64/lib/python3.10/site-packages/scipy/ndimage/_filters.py", line 38, in <module>
    from . import _ni_docstrings
  File "C:/omnetpp-6.0.3-windows-x86_64/omnetpp-6.0.3/tools/win32.x86_64/mingw64/lib/python3.10/site-packages/scipy/ndimage/_ni_docstrings.py", line 208, in <module>
    docfiller = doccer.filldoc(docdict)
AttributeError: module 'scipy._lib.doccer' has no attribute 'filldoc'
no
configure: error: Some Python modules required by the IDE were not found:

I have scipy and numpy installed. Please kindly help with the problem and the possible solution.
Thank you.

**Comment by MannyUbom** [comment]
> Honestly, I have no idea why the pre-packaged scipy module fails to load. On Windows, you don't have to install anything as all the dependencies are packaged. I can only think that maybe the downloaded ZIP file is damaged. Please note also that the built-in UNZIP functionality of Windows 10 used to be broken, so depending on the OS patch level that might be also the issue.
> 
> I would recommend:
> 
> * try to extract with a 3rd party zip extractor
> * Use OMNeT++ 6.1 instead of 6.0.3
> * Install an Ubuntu VM in WSL (i.e. install Ubuntu from the MS Store) and install the linux version of OMNeT++ there (don't be afraid of Linux, the Windows version of OMNeT++ essentially gives a console window that tries to emulate Linux anyway
> * Install omnetpp with [opp_env](https://omnetpp.org/opp_env) (which is essentially the same as the above point, but saves you the installaytion of dependencies)

Thank you so very much for your assistance. I am most grateful.
I actually used WinRAR to unzip the OMNeTpp. I will try to install OMNetpp 6.1 and see if it solves the problem. 
I have also quickly installed the Ubuntu OS but hmmmmm my Linux is not there yet. I hope I can move with it. 
Will update you on the outcome of these trials. 
Thank you very much.
UbomManny

**Comment by MannyUbom** [comment]
Thank you OMNet++ 6.1 solved the problem.
