### ISSUE TITLE
Cannot export csv results

### ISSUE THREAD

**Issue by juansebasoz** [omnetpp/omnetpp#1277]
**Platform**
 - OMNeT++ version:6.0.1
 - Inet 4.5
 - Simu5G 1.2.2 
 - OS: Ubuntu 20.04 on Docker 
 - VNC server to remote connection
 - Java version: 17.04

I created a container with all required packages to run Simu5G. I can run the simulations without problem, it creates the .sca and .vec files. I can also create the .anf file to analyze the results, the error comes when I try to export the data as .csv, I get the following error:

java.lang.RuntimeException: Error writing CSV file
	at org.omnetpp.scave.engine.ScaveEngineJNI.Exporter_saveResults__SWIG_0(Native Method)
	at org.omnetpp.scave.engine.Exporter.saveResults(Exporter.java:56)
	at org.omnetpp.scave.wizard.ScaveExportWizard.lambda$1(ScaveExportWizard.java:172)
	at org.omnetpp.scave.engine.ResultFileManager.runWithLock(ResultFileManager.java:105)
	at org.omnetpp.scave.engine.ResultFileManager.runWithReadLock(ResultFileManager.java:94)
	at org.omnetpp.scave.wizard.ScaveExportWizard.lambda$0(ScaveExportWizard.java:172)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

![image](https://github.com/user-attachments/assets/e0bf4c39-32c6-4a1e-ac3b-3614e07350b7)

**Comment by rhornig** [comment]
make sure that the process has write access to the directory where you want to export you CSV file. Docker container might be tricky to set up with proper access rights. This is a normal file write error reported by the OS.
