### ISSUE TITLE
omnet ide cannot create makefiles

### ISSUE THREAD

**Issue by odom11** [omnetpp/omnetpp#751]
**Platform**
 - OMNeT++ version: 5.4.1 as well experimental 6.0
 - OS: arch kernel 4.19.12

**Describe the bug**

cannot create makefiles (and thus cannot run simulations from the IDE). Commandline approach
with opp_makemake (and subsequent make) works fine, however I cannot use the ide for building/simulation.

the .log file in the .metadata sample contains the following

<details>
<p>
!SESSION 2018-12-29 17:52:06.827 -----------------------------------------------
eclipse.buildId=6.0.0.180809-1548ee5f82
java.version=10.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.egit.core 2 0 2018-12-29 17:52:18.026
!MESSAGE Builtin LFS support not present/detected
!STACK 0
java.lang.ClassNotFoundException: org.eclipse.jgit.lfs.BuiltinLFS cannot be found by org.eclipse.egit.core_5.0.0.201806131550-r
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:508)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:419)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:411)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:291)
	at org.eclipse.egit.core.Activator.registerBuiltinLFS(Activator.java:279)
	at org.eclipse.egit.core.Activator.start(Activator.java:212)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1002)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:354)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:468)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:114)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:505)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:328)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:392)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:36)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:454)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:419)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:411)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at org.eclipse.egit.ui.Activator$RepositoryChangeScanner.<init>(Activator.java:921)
	at org.eclipse.egit.ui.Activator.setupRepoChangeScanner(Activator.java:1034)
	at org.eclipse.egit.ui.Activator.start(Activator.java:336)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1002)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:354)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:468)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:114)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:505)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:328)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:392)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:470)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:419)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:411)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:609)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:177)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:931)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:60)
	at org.eclipse.ui.internal.services.WorkbenchServiceRegistry.getSourceProviders(WorkbenchServiceRegistry.java:174)
	at org.eclipse.ui.internal.services.SourceProviderService.readRegistry(SourceProviderService.java:104)
	at org.eclipse.ui.internal.Workbench$34.runWithException(Workbench.java:2378)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:32)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:233)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:144)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5831)
	at org.eclipse.ui.internal.StartupThreading.runWithoutExceptions(StartupThreading.java:95)
	at org.eclipse.ui.internal.Workbench.initializeDefaultServices(Workbench.java:2373)
	at org.eclipse.ui.internal.Workbench.init(Workbench.java:1654)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2859)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1471)

!ENTRY org.omnetpp.main 1 0 2018-12-29 17:52:19.775
!MESSAGE OMNeT++ IDE 6.0.0.180809-1548ee5f82 started.

!ENTRY org.eclipse.help.base 2 0 2018-12-29 17:52:33.518
!MESSAGE Unable to consume Lucene index from bundle 'org.eclipse.cdt.doc.user_5.4.0.201807181141 [77]'. The index should be rebuilt with Lucene 7.0.0

!ENTRY org.python.pydev.shared_core 4 4 2018-12-29 17:53:03.880
!MESSAGE Python not configured.
!STACK 0
org.python.pydev.core.NotConfiguredInterpreterException: Python not configured.
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.getDefaultInterpreterInfo(AbstractInterpreterManager.java:239)
	at org.python.pydev.plugin.nature.PythonNature.getProjectInterpreter(PythonNature.java:1339)
	at org.python.pydev.plugin.nature.PythonPathNature.getVariableSubstitution(PythonPathNature.java:520)
	at org.python.pydev.plugin.nature.PythonPathNature.getVariableSubstitution(PythonPathNature.java:503)
	at org.python.pydev.core.docutils.StringSubstitution.<init>(StringSubstitution.java:57)
	at org.python.pydev.plugin.nature.PythonPathNature.getOnlyProjectPythonPathStr(PythonPathNature.java:166)
	at org.python.pydev.plugin.nature.PythonNature$RebuildPythonNatureModules.run(PythonNature.java:134)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

!ENTRY org.python.pydev.shared_core 4 4 2018-12-29 17:53:03.925
!MESSAGE Info: Rebuilding internal caches: /home/ich/libs/omnet/6.0_pre/samples/.metadata/.plugins/org.eclipse.core.resources/.projects/resultfiles/com.python.pydev.analysis/AdditionalProjectInterpreterInfo.pydevinfo (Expected error to be provided and got no error!)

!ENTRY org.python.pydev.shared_core 4 4 2018-12-29 17:53:03.931
!MESSAGE Info: Rebuilding internal caches: /home/ich/libs/omnet/6.0_pre/samples/.metadata/.plugins/org.eclipse.core.resources/.projects/pythoncharts/com.python.pydev.analysis/AdditionalProjectInterpreterInfo.pydevinfo (Expected error to be provided and got no error!)

!ENTRY org.eclipse.launchbar.core 2 0 2018-12-29 17:53:12.649
!MESSAGE Enablement expression is missing for descriptor type org.eclipse.cdt.debug.core.coreBuildDescriptorType

!ENTRY org.eclipse.launchbar.core 2 0 2018-12-29 17:53:12.650
!MESSAGE Enablement expression is missing for config provider for org.eclipse.cdt.debug.core.coreBuildDescriptorType

!ENTRY org.eclipse.launchbar.core 2 0 2018-12-29 17:53:12.651
!MESSAGE Enablement expression is missing for config provider for org.eclipse.cdt.debug.core.coreBuildDescriptorType

!ENTRY org.eclipse.cdt.core 1 0 2018-12-29 17:53:23.088
!MESSAGE Indexed 'neddemo' (1 sources, 391 headers) in 14 sec: 37,085 declarations; 58,630 references; 0 unresolved inclusions; 0 syntax errors; 5 unresolved names (0.0052%)

!ENTRY org.eclipse.core.resources 4 2 2018-12-29 17:53:29.831
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:44)
	at java.base/java.lang.String.charAt(String.java:692)
	at org.omnetpp.cdt.build.MetaMakemake.toAbsolute(MetaMakemake.java:361)
	at org.omnetpp.cdt.build.MetaMakemake.toAbsolute(MetaMakemake.java:356)
	at org.omnetpp.cdt.build.MetaMakemake.getLocalIncludePath(MetaMakemake.java:220)
	at org.omnetpp.cdt.build.MetaMakemake.getIncludePath(MetaMakemake.java:188)
	at org.omnetpp.cdt.build.MetaMakemake.translateOptions(MetaMakemake.java:109)
	at org.omnetpp.cdt.build.MetaMakemake.generateMakefile(MetaMakemake.java:53)
	at org.omnetpp.cdt.build.MakefileBuilder.generateMakefileFor(MakefileBuilder.java:352)
	at org.omnetpp.cdt.build.MakefileBuilder.generateMakefiles(MakefileBuilder.java:335)
	at org.omnetpp.cdt.build.MakefileBuilder.build(MakefileBuilder.java:78)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:795)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:216)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:259)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:312)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:315)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:367)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:388)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:501)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:408)
	at org.eclipse.ui.actions.BuildAction$1.runInWorkspace(BuildAction.java:288)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

!ENTRY org.eclipse.cdt.core 1 0 2018-12-29 17:53:30.200
!MESSAGE Indexed 'histograms' (1 sources, 391 headers) in 7.11 sec: 37,137 declarations; 59,367 references; 0 unresolved inclusions; 0 syntax errors; 5 unresolved names (0.0052%)

!ENTRY org.eclipse.core.resources 4 75 2018-12-29 17:53:30.267
!MESSAGE Errors occurred during the build.
!SUBENTRY 1 org.omnetpp.cdt 4 75 2018-12-29 17:53:30.267
!MESSAGE Errors running builder 'OMNeT++ Makefile Builder' on project 'tictoc'.
!STACK 0
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:44)
	at java.base/java.lang.String.charAt(String.java:692)
	at org.omnetpp.cdt.build.MetaMakemake.toAbsolute(MetaMakemake.java:361)
	at org.omnetpp.cdt.build.MetaMakemake.toAbsolute(MetaMakemake.java:356)
	at org.omnetpp.cdt.build.MetaMakemake.getLocalIncludePath(MetaMakemake.java:220)
	at org.omnetpp.cdt.build.MetaMakemake.getIncludePath(MetaMakemake.java:188)
	at org.omnetpp.cdt.build.MetaMakemake.translateOptions(MetaMakemake.java:109)
	at org.omnetpp.cdt.build.MetaMakemake.generateMakefile(MetaMakemake.java:53)
	at org.omnetpp.cdt.build.MakefileBuilder.generateMakefileFor(MakefileBuilder.java:352)
	at org.omnetpp.cdt.build.MakefileBuilder.generateMakefiles(MakefileBuilder.java:335)
	at org.omnetpp.cdt.build.MakefileBuilder.build(MakefileBuilder.java:78)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:795)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:216)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:259)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:312)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:315)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:367)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:388)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:501)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:408)
	at org.eclipse.ui.actions.BuildAction$1.runInWorkspace(BuildAction.java:288)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

!ENTRY org.eclipse.cdt.core 1 0 2018-12-29 17:53:38.542
!MESSAGE Indexed 'dyna' (5 sources, 405 headers) in 8.33 sec: 40,121 declarations; 64,884 references; 0 unresolved inclusions; 0 syntax errors; 6 unresolved names (0.0057%)

!ENTRY org.eclipse.cdt.core 1 0 2018-12-29 17:53:45.359
!MESSAGE Indexed 'embedding' (5 sources, 393 headers) in 6.81 sec: 37,202 declarations; 59,282 references; 0 unresolved inclusions; 0 syntax errors; 5 unresolved names (0.0052%)

!ENTRY org.eclipse.cdt.core 1 0 2018-12-29 17:53:52.455
!MESSAGE Indexed 'routing' (6 sources, 411 headers) in 7.08 sec: 40,899 declarations; 67,095 references; 0 unresolved inclusions; 0 syntax errors; 8 unresolved names (0.0074%)

!ENTRY org.eclipse.cdt.core 1 0 2018-12-29 17:53:58.394
!MESSAGE Indexed 'cqn' (2 sources, 391 headers) in 5.14 sec: 37,142 declarations; 58,931 references; 0 unresolved inclusions; 0 syntax errors; 5 unresolved names (0.0052%)

!ENTRY org.eclipse.cdt.core 1 0 2018-12-29 17:54:04.741
!MESSAGE Indexed 'queueinglib' (20 sources, 436 headers) in 6.33 sec: 43,959 declarations; 71,693 references; 0 unresolved inclusions; 0 syntax errors; 8 unresolved names (0.0069%)

!ENTRY org.eclipse.cdt.core 1 0 2018-12-29 17:54:09.813
!MESSAGE Indexed 'embedding2' (4 sources, 393 headers) in 5.07 sec: 37,223 declarations; 59,601 references; 0 unresolved inclusions; 0 syntax errors; 5 unresolved names (0.0052%)

!ENTRY org.eclipse.cdt.core 1 0 2018-12-29 17:54:25.397
!MESSAGE Indexed 'osg-satellites' (6 sources, 739 headers) in 15.4 sec: 92,299 declarations; 158,351 references; 0 unresolved inclusions; 0 syntax errors; 32 unresolved names (0.013%)

!ENTRY org.eclipse.cdt.core 1 0 2018-12-29 17:54:31.466
!MESSAGE Indexed 'sockets' (12 sources, 441 headers) in 6.06 sec: 42,230 declarations; 69,264 references; 0 unresolved inclusions; 0 syntax errors; 8 unresolved names (0.0072%)

!ENTRY org.eclipse.core.resources 4 2 2018-12-29 17:54:35.348
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:44)
	at java.base/java.lang.String.charAt(String.java:692)
	at org.omnetpp.cdt.build.MetaMakemake.toAbsolute(MetaMakemake.java:361)
	at org.omnetpp.cdt.build.MetaMakemake.toAbsolute(MetaMakemake.java:356)
	at org.omnetpp.cdt.build.MetaMakemake.getLocalIncludePath(MetaMakemake.java:220)
	at org.omnetpp.cdt.build.MetaMakemake.getIncludePath(MetaMakemake.java:188)
	at org.omnetpp.cdt.build.MetaMakemake.translateOptions(MetaMakemake.java:109)
	at org.omnetpp.cdt.build.MetaMakemake.generateMakefile(MetaMakemake.java:53)
	at org.omnetpp.cdt.build.MakefileBuilder.generateMakefileFor(MakefileBuilder.java:352)
	at org.omnetpp.cdt.build.MakefileBuilder.generateMakefiles(MakefileBuilder.java:335)
	at org.omnetpp.cdt.build.MakefileBuilder.build(MakefileBuilder.java:78)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:795)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:216)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:259)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:312)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:315)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:367)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:388)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:501)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:408)
	at org.eclipse.ui.actions.BuildAction$1.runInWorkspace(BuildAction.java:288)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

!ENTRY org.eclipse.core.resources 4 75 2018-12-29 17:54:35.578
!MESSAGE Errors occurred during the build.
!SUBENTRY 1 org.omnetpp.cdt 4 75 2018-12-29 17:54:35.578
!MESSAGE Errors running builder 'OMNeT++ Makefile Builder' on project 'tictoc'.
!STACK 0
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:44)
	at java.base/java.lang.String.charAt(String.java:692)
	at org.omnetpp.cdt.build.MetaMakemake.toAbsolute(MetaMakemake.java:361)
	at org.omnetpp.cdt.build.MetaMakemake.toAbsolute(MetaMakemake.java:356)
	at org.omnetpp.cdt.build.MetaMakemake.getLocalIncludePath(MetaMakemake.java:220)
	at org.omnetpp.cdt.build.MetaMakemake.getIncludePath(MetaMakemake.java:188)
	at org.omnetpp.cdt.build.MetaMakemake.translateOptions(MetaMakemake.java:109)
	at org.omnetpp.cdt.build.MetaMakemake.generateMakefile(MetaMakemake.java:53)
	at org.omnetpp.cdt.build.MakefileBuilder.generateMakefileFor(MakefileBuilder.java:352)
	at org.omnetpp.cdt.build.MakefileBuilder.generateMakefiles(MakefileBuilder.java:335)
	at org.omnetpp.cdt.build.MakefileBuilder.build(MakefileBuilder.java:78)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:795)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:216)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:259)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:312)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:315)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:367)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:388)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:501)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:408)
	at org.eclipse.ui.actions.BuildAction$1.runInWorkspace(BuildAction.java:288)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

!ENTRY org.eclipse.cdt.core 1 0 2018-12-29 17:54:36.620
!MESSAGE Indexed 'fifo' (4 sources, 393 headers) in 5.15 sec: 37,160 declarations; 59,061 references; 0 unresolved inclusions; 0 syntax errors; 5 unresolved names (0.0052%)

!ENTRY org.eclipse.cdt.core 1 0 2018-12-29 17:54:41.872
!MESSAGE Indexed 'queueinglibext' (1 sources, 395 headers) in 5.2 sec: 37,109 declarations; 58,669 references; 0 unresolved inclusions; 0 syntax errors; 5 unresolved names (0.0052%)

!ENTRY org.eclipse.cdt.core 1 0 2018-12-29 17:54:55.067
!MESSAGE Indexed 'osg-earth' (6 sources, 722 headers) in 13.2 sec: 90,605 declarations; 155,718 references; 0 unresolved inclusions; 0 syntax errors; 32 unresolved names (0.013%)

!ENTRY org.eclipse.cdt.core 1 0 2018-12-29 17:54:55.069
!MESSAGE Indexed 'canvas' (0 sources, 0 headers) in 0 sec: 0 declarations; 0 references; 0 unresolved inclusions; 0 syntax errors; 0 unresolved names (0%)

!ENTRY org.eclipse.cdt.core 1 0 2018-12-29 17:55:05.179
!MESSAGE Indexed 'osg-indoor' (3 sources, 552 headers) in 10.1 sec: 75,812 declarations; 125,802 references; 0 unresolved inclusions; 0 syntax errors; 23 unresolved names (0.011%)

!ENTRY org.eclipse.cdt.core 1 0 2018-12-29 17:55:14.864
!MESSAGE Indexed 'osg-intro' (2 sources, 546 headers) in 9.68 sec: 75,512 declarations; 124,850 references; 0 unresolved inclusions; 0 syntax errors; 23 unresolved names (0.011%)

!ENTRY org.eclipse.cdt.core 1 0 2018-12-29 17:55:20.990
!MESSAGE Indexed 'tictoc' (24 sources, 415 headers) in 6.05 sec: 42,004 declarations; 71,469 references; 0 unresolved inclusions; 0 syntax errors; 6 unresolved names (0.0053%)

!ENTRY org.eclipse.cdt.core 1 0 2018-12-29 17:55:25.564
!MESSAGE Indexed 'aloha' (2 sources, 400 headers) in 4.57 sec: 39,903 declarations; 63,841 references; 0 unresolved inclusions; 0 syntax errors; 6 unresolved names (0.0058%)

!ENTRY org.eclipse.cdt.core 1 0 2018-12-29 17:55:30.781
!MESSAGE Indexed 'hypercube' (4 sources, 409 headers) in 4.71 sec: 39,978 declarations; 63,747 references; 0 unresolved inclusions; 0 syntax errors; 6 unresolved names (0.0058%)

!ENTRY org.eclipse.core.resources 4 2 2018-12-29 18:04:09.225
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:44)
	at java.base/java.lang.String.charAt(String.java:692)
	at org.omnetpp.cdt.build.MetaMakemake.toAbsolute(MetaMakemake.java:361)
	at org.omnetpp.cdt.build.MetaMakemake.toAbsolute(MetaMakemake.java:356)
	at org.omnetpp.cdt.build.MetaMakemake.getLocalIncludePath(MetaMakemake.java:220)
	at org.omnetpp.cdt.build.MetaMakemake.getIncludePath(MetaMakemake.java:188)
	at org.omnetpp.cdt.build.MetaMakemake.translateOptions(MetaMakemake.java:109)
	at org.omnetpp.cdt.build.MetaMakemake.generateMakefile(MetaMakemake.java:53)
	at org.omnetpp.cdt.build.MakefileBuilder.generateMakefileFor(MakefileBuilder.java:352)
	at org.omnetpp.cdt.build.MakefileBuilder.generateMakefiles(MakefileBuilder.java:335)
	at org.omnetpp.cdt.build.MakefileBuilder.build(MakefileBuilder.java:78)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:795)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:216)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:259)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:312)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:315)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:367)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:388)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:501)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:408)
	at org.eclipse.ui.actions.BuildAction$1.runInWorkspace(BuildAction.java:288)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

!ENTRY org.eclipse.core.resources 4 75 2018-12-29 18:04:09.489
!MESSAGE Errors occurred during the build.
!SUBENTRY 1 org.omnetpp.cdt 4 75 2018-12-29 18:04:09.490
!MESSAGE Errors running builder 'OMNeT++ Makefile Builder' on project 'tictoc'.
!STACK 0
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:44)
	at java.base/java.lang.String.charAt(String.java:692)
	at org.omnetpp.cdt.build.MetaMakemake.toAbsolute(MetaMakemake.java:361)
	at org.omnetpp.cdt.build.MetaMakemake.toAbsolute(MetaMakemake.java:356)
	at org.omnetpp.cdt.build.MetaMakemake.getLocalIncludePath(MetaMakemake.java:220)
	at org.omnetpp.cdt.build.MetaMakemake.getIncludePath(MetaMakemake.java:188)
	at org.omnetpp.cdt.build.MetaMakemake.translateOptions(MetaMakemake.java:109)
	at org.omnetpp.cdt.build.MetaMakemake.generateMakefile(MetaMakemake.java:53)
	at org.omnetpp.cdt.build.MakefileBuilder.generateMakefileFor(MakefileBuilder.java:352)
	at org.omnetpp.cdt.build.MakefileBuilder.generateMakefiles(MakefileBuilder.java:335)
	at org.omnetpp.cdt.build.MakefileBuilder.build(MakefileBuilder.java:78)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:795)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:216)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:259)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:312)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:315)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:367)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:388)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:501)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:408)
	at org.eclipse.ui.actions.BuildAction$1.runInWorkspace(BuildAction.java:288)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
</p>
</details>

**To Reproduce**
Help the development team to reproduce the issue.
Provide step-by-step instructions, code examples, etc.
- called omnetpp from terminal to start the IDE
- File -> import -> General -> Existing project on the samples folder
- went to tictoc directory -> leftclick -> build project
- obtained the following error message from the ide:

Errors occurred during the build.
Errors running builder 'OMNeT++ Makefile Builder' on project 'tictoc'.
String index out of range: 0

**Comment by rhornig** [comment]
I was not able to reproduce this here so:

@odom11 Could you please attach the `<omnetpproot>/samples/.metadata/.log` file? Delete this file (to make it as short as possible), then invoke the error and then attach the generated log file.

**Comment by rhornig** [comment]
5.5 released. Please reopen if you still experience this issue.

**Comment by Chibikuri** [comment]
Were there any solutions for this issue? I have the same issue on OMNeT++ 6.0.
