### ISSUE TITLE
Install Core Simulation modules error

### ISSUE THREAD

**Issue by shan-rak** [omnetpp/omnetpp#807]
**Platform**
 - OMNeT++ version: [ 5.6]
 - OS: [Windows 10]

**Describe the bug**
Install Core Simulation modules error
An internal error occurred during: "Download project descriptors".
Invalid thread access.

**To Reproduce**
1. Launch OMNET IDE
2. Load Workspace
3. Click on Help->Install Core Simulation Modules

![image](https://user-images.githubusercontent.com/63794395/79459988-ce2bd580-8011-11ea-98aa-8050ccc27449.png)

**Comment by rhornig** [comment]
This was caused by the server not returning correct descriptor files. It should work now.

**Comment by tariqghd** [comment]
hello 

I have same error
An internal error occurred during: "Download project descriptors".
Invalid thread access

**Comment by elmanol** [comment]
I get the same error for version 5.6.2. This is the output in the logfile at /.metadata/.log file. 

```
!ENTRY org.omnetpp.common 4 0 2020-11-25 01:06:05.105
!MESSAGE An error occurred while downloading the list of models available for installation from https://models.omnetpp.org/descriptors/omnetpp-5.6/descriptors.txt
!STACK 0
java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 403 for URL: https://models.omnetpp.org/descriptors/omnetpp-5.6/descriptors.txt
	at org.omnetpp.ide.installer.InstallSimulationModelsDialog.downloadProjectDescriptions(InstallSimulationModelsDialog.java:91)
	at org.omnetpp.ide.installer.InstallSimulationModelsDialog$6.run(InstallSimulationModelsDialog.java:243)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://models.omnetpp.org/descriptors/omnetpp-5.6/descriptors.txt
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.omnetpp.ide.installer.InstallSimulationModelsDialog.downloadProjectDescriptions(InstallSimulationModelsDialog.java:74)
	... 2 more

!ENTRY org.eclipse.core.jobs 4 2 2020-11-25 01:06:05.123
!MESSAGE An internal error occurred during: "Download project descriptors".
!STACK 0
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4720)
	at org.eclipse.swt.SWT.error(SWT.java:4635)
	at org.eclipse.swt.SWT.error(SWT.java:4606)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:452)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:370)
	at org.eclipse.swt.widgets.Text.getText(Text.java:1394)
	at org.eclipse.jface.dialogs.TitleAreaDialog.updateMessage(TitleAreaDialog.java:627)
	at org.eclipse.jface.dialogs.TitleAreaDialog.setErrorMessage(TitleAreaDialog.java:422)
	at org.omnetpp.ide.installer.InstallSimulationModelsDialog$6.run(InstallSimulationModelsDialog.java:253)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
