### ISSUE TITLE
integrate vector operation causes error

### ISSUE THREAD

**Issue by edlongman** [omnetpp/omnetpp#901]
**Platform**
 - OMNeT++ version: 6
 - OS: Windows

**Describe the bug**
```
An error occurred. Traceback (most recent call last):
  File "<string>", line 25, in <module>
  File "F:/Apps/omnetpp6/ide/plugins/org.omnetpp.scave.pychart_6.0.0.210727-c1ec2ec2fa/python/omnetpp/scave/utils.py", line 851, in perform_vector_ops
    raise type(e)(str(e) + context).with_traceback(sys.exc_info()[2]) # re-throw with context
  File "F:/Apps/omnetpp6/ide/plugins/org.omnetpp.scave.pychart_6.0.0.210727-c1ec2ec2fa/python/omnetpp/scave/utils.py", line 848, in perform_vector_ops
    df = _perform_vector_op(df, line)
  File "F:/Apps/omnetpp6/ide/plugins/org.omnetpp.scave.pychart_6.0.0.210727-c1ec2ec2fa/python/omnetpp/scave/utils.py", line 874, in _perform_vector_op
    df = _apply_vector_op(df, name + arglist_str, function, *args, **kwargs)
  File "F:/Apps/omnetpp6/ide/plugins/org.omnetpp.scave.pychart_6.0.0.210727-c1ec2ec2fa/python/omnetpp/scave/utils.py", line 938, in _apply_vector_op
    clone = clone.transform(lambda row: process(row.copy()) if not condition or condition(row) else row, axis='columns')
  File "F:/Apps/omnetpp6/tools/win64/mingw64/lib/python3.8/site-packages/pandas/core/frame.py", line 6728, in transform
    return self.T.transform(func, *args, **kwargs).T
  File "F:/Apps/omnetpp6/tools/win64/mingw64/lib/python3.8/site-packages/pandas/core/frame.py", line 6729, in transform
    return super().transform(func, *args, **kwargs)
  File "F:/Apps/omnetpp6/tools/win64/mingw64/lib/python3.8/site-packages/pandas/core/generic.py", line 10425, in transform
    result = self.agg(func, *args, **kwargs)
  File "F:/Apps/omnetpp6/tools/win64/mingw64/lib/python3.8/site-packages/pandas/core/frame.py", line 6710, in aggregate
    return self.apply(func, axis=axis, args=args, **kwargs)
  File "F:/Apps/omnetpp6/tools/win64/mingw64/lib/python3.8/site-packages/pandas/core/frame.py", line 6878, in apply
    return op.get_result()
  File "F:/Apps/omnetpp6/tools/win64/mingw64/lib/python3.8/site-packages/pandas/core/apply.py", line 186, in get_result
    return self.apply_standard()
  File "F:/Apps/omnetpp6/tools/win64/mingw64/lib/python3.8/site-packages/pandas/core/apply.py", line 295, in apply_standard
    result = libreduction.compute_reduction(
  File "pandas/_libs/reduction.pyx", line 620, in pandas._libs.reduction.compute_reduction
  File "pandas/_libs/reduction.pyx", line 128, in pandas._libs.reduction.Reducer.get_result
  File "F:/Apps/omnetpp6/ide/plugins/org.omnetpp.scave.pychart_6.0.0.210727-c1ec2ec2fa/python/omnetpp/scave/utils.py", line 938, in <lambda>
    clone = clone.transform(lambda row: process(row.copy()) if not condition or condition(row) else row, axis='columns')
  File "F:/Apps/omnetpp6/ide/plugins/org.omnetpp.scave.pychart_6.0.0.210727-c1ec2ec2fa/python/omnetpp/scave/utils.py", line 935, in process
    row["vectime"].flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array in Vector Operations line 1 "integrate(interpolation='sample-hold')"
```

**To Reproduce**
Use the integrate as a vector operation on a linechart

**Related**
https://github.com/pandas-dev/pandas/issues/24839

Tried `pip install numpy==1.15.4 `, got error: 

**Steps  and debugging**
Pip didn't work due to wrong path in `~/tools/win64/mingw64/bin/pip-script.py` and `~/tools/win64/mingw64/bin/pip3-script.py` - Referred to `E:\omnetpp-pre9\....`

Trying `pip install numpy` gave
```
....
ValueError: python38.dll not found in ['MingwDir'...]
Looking for python38.dll
    ----------------------------------------
ERROR: Command errored out with exit status 1...
```

Reinstalled python
```
pacman -S mingw-w64-x86_64-python
```

Reinstalled numpy
```
pacman -S numpy
```

None of these work.

**Comment by torokati44** [comment]
Thanks for the report, this was fixed for 6.0.
