### ISSUE TITLE
Matplotlib Scatter plot cannot handle long axis titles

### ISSUE THREAD

**Issue by edlongman** [omnetpp/omnetpp#915]
**Platform**
 - OMNeT++ version: 6-pre13
 - OS: Windows 10

**Describe the bug**
When plotting a very large number of scalars in a scatter plot, it fails when there are more than 128 scalars.

This is to do with the Y label having too many elements or something!

<details> 
  <summary>Stack trace:</summary>

```
py4j.Py4JException: An exception was raised by the Python Proxy. Return Message: Traceback (most recent call last):
  File "C:/omnetpp6/ide/plugins/org.omnetpp.scave.pychart_6.0.0.211015-f5e4ca7a15/python/py4j/clientserver.py", line 581, in _call_proxy
    return_value = getattr(self.pool[obj_id], method)(*params)
  File "C:/omnetpp6/ide/plugins/org.omnetpp.scave.pychart_6.0.0.211015-f5e4ca7a15/python/omnetpp/internal/backend_SWTAgg.py", line 209, in resizeEvent
    self._resize(width, height)
  File "C:/omnetpp6/ide/plugins/org.omnetpp.scave.pychart_6.0.0.211015-f5e4ca7a15/python/omnetpp/internal/backend_SWTAgg.py", line 206, in _resize
    FigureCanvasBase.resize_event(self)
  File "C:/omnetpp6/tools/win64/mingw64/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1768, in resize_event
    self.draw_idle()
  File "C:/omnetpp6/tools/win64/mingw64/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2012, in draw_idle
    self.draw(*args, **kwargs)
  File "C:/omnetpp6/ide/plugins/org.omnetpp.scave.pychart_6.0.0.211015-f5e4ca7a15/python/omnetpp/internal/backend_SWTAgg.py", line 327, in draw
    FigureCanvasAgg.draw(self)
  File "C:/omnetpp6/tools/win64/mingw64/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "C:/omnetpp6/tools/win64/mingw64/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:/omnetpp6/tools/win64/mingw64/lib/python3.8/site-packages/matplotlib/figure.py", line 1863, in draw
    mimage._draw_list_compositing_images(
  File "C:/omnetpp6/tools/win64/mingw64/lib/python3.8/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:/omnetpp6/tools/win64/mingw64/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:/omnetpp6/tools/win64/mingw64/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "C:/omnetpp6/tools/win64/mingw64/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 2747, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "C:/omnetpp6/tools/win64/mingw64/lib/python3.8/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:/omnetpp6/tools/win64/mingw64/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:/omnetpp6/tools/win64/mingw64/lib/python3.8/site-packages/matplotlib/axis.py", line 1178, in draw
    self.label.draw(renderer)
  File "C:/omnetpp6/tools/win64/mingw64/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:/omnetpp6/tools/win64/mingw64/lib/python3.8/site-packages/matplotlib/text.py", line 727, in draw
    textrenderer.draw_text(gc, x, y, clean_line,
  File "C:/omnetpp6/tools/win64/mingw64/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 202, in draw_text
    font.draw_glyphs_to_bitmap(
RuntimeError: In draw_glyphs_to_bitmap: Could not convert glyph to bitmap (error code 0x62)
```
</details>

It may also affect other plots but haven't tested it.

**To Reproduce**
Run a simulation producing more than 128 scalars over some kind of iterated variable. 

Setup a matplotlib scatter plot with lots of scalars plotted on the itervar.

**Workaround**
Give the plot a Y Label instead of letting it automatically determine the label.

**Comment by torokati44** [comment]
Thanks for the report!

My guess is that the problem is not the number of scalars, and 128 is not a clear threshold. Instead, the names of all the different scalars are all concatenated for the automatic Y axis label, which likely ends up too long for the graphical backend to be rendered all at once.

To verify this, could you please try manually setting a _very_ long (1..10k characters - easy to produce with recursive copy-pasting in the Properties dialog) axis label? I tried this myself, but since my system is different (I use Linux), it failed in a different way.

The scatter chart template has been improved since 6.0pre13, so that it no longer tries to set uselessly long axis labels or plot titles, motivated exactly by these kinds of issues. (Well, not this particular technical limitation, but the quality of the chart for human consumption.)

**Comment by edlongman** [comment]
Indeed, you are correct that it is just the length. But not actually the number of characters, it's the physical rendered length.
If you have a title of `m`x2426 it breaks, but with `l`x8456 it breaks

**Comment by torokati44** [comment]
The original issue with the scatter chart template was fixed, the remaining limitation is that of matplotlib.
