### ISSUE TITLE
OMNeT++ 6.0.1 & tictoc8: Internal error (Unhandled event loop exception) when opening sequence chart

### ISSUE THREAD

**Issue by windy32** [omnetpp/omnetpp#939]
**Platform**
 - OMNeT++ version: 6.0.1
 - OS: Linux Mint 20.2 MATE 64 bit

**Describe the bug**
When I tested the tictoc8 tutorial with OMNeT++ 6.0.1 and tried to open the generated elog with OMNeT++ IDE, the new tab crashed. It says:

```
Internal error - please tweak the settings and refresh
Try changing the zoom factor, scroll position, display modes, eventlog filter parameters, etc.
to prevent the error from happening again, then press Refresh.
We are sorry for the inconvenience.
```

![screenshot163](https://user-images.githubusercontent.com/12342773/191195580-1bd5b181-9a27-4e06-9c0f-f30ae78f7f96.png)

Tutorial URL: https://docs.omnetpp.org/tutorials/tictoc/part3/

The content of the error log is:

```
Unhandled event loop exception

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.omnetpp.common.eventlog.EventLogInput.runWithProgressMonitor(EventLogInput.java:584)
	at org.omnetpp.sequencechart.widgets.SequenceChart.collectVisibleObjectsAtPosition(SequenceChart.java:5067)
	at org.omnetpp.sequencechart.widgets.SequenceChart$25.mouseUp(SequenceChart.java:5986)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:224)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5895)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1515)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5126)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4581)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:443)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:352)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:468)
	at org.omnetpp.common.ui.TimeTriggeredProgressMonitorDialog2.access$0(TimeTriggeredProgressMonitorDialog2.java:1)
	at org.omnetpp.common.ui.TimeTriggeredProgressMonitorDialog2.run(TimeTriggeredProgressMonitorDialog2.java:163)
	at org.omnetpp.common.eventlog.EventLogProgressManager.runWithProgressMonitor(EventLogProgressManager.java:42)
	at org.omnetpp.common.eventlog.EventLogInput.runWithProgressMonitor(EventLogInput.java:565)
	... 30 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.omnetpp.eventlog.IEvent.getEventNumber()" because "event" is null
	at org.omnetpp.sequencechart.widgets.SequenceChart.isInitializationEvent(SequenceChart.java:5401)
	at org.omnetpp.sequencechart.widgets.SequenceChart$20.run(SequenceChart.java:5117)
	at org.omnetpp.common.eventlog.EventLogInput$2.run(EventLogInput.java:570)
	at org.omnetpp.common.eventlog.EventLogProgressManager$1.run(EventLogProgressManager.java:50)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:434)
	... 36 more
[tictoc8.zip](https://github.com/omnetpp/omnetpp/files/9605154/tictoc8.zip)

eclipse.buildId=6.0.1.220831-e4f07d04b8
java.version=17.0.4
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

This is a continuation of log file /home/feng32/Downloads/omnetpp-6.0.1/tutorial/.metadata/.bak_5.log
Created Time: 2022-09-19 10:12:10.042
```

**To Reproduce**
Add related ned, cc and ini files into a new project (provided in the attachedment), run tictoc8.ned. Then enable eventlog, run with full animation, wait a few seconds, pause, and close the window.

An elog file will be generated. When opening the elog file in IDE, the error will reproduce.

The elog file is also provided in the attachment. Opening the file directly should also reproduce the issue.

[tictoc8.zip](https://github.com/omnetpp/omnetpp/files/9605172/tictoc8.zip)

**Comment by levy** [comment]
Thanks for the bug report. This will be fixed in the next patch release.

As a workaround, you can paste the following line into the elog file:

    E # 0 t 0 m 1 ce -1 msg -1

copy the above before the ```E # 1 ...```, and make sure the line is separated by a blank line before and after.
